### ISSUE TITLE
Create post-workshop assessment

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#3]
The post-workshop assessment we used with Joey's: http://goo.gl/forms/sBllBslPwx

Others?

**Comment by stephwright** [comment]
Started a draft [here](../blob/master/TEMPLATES/postassess.md).

**Comment by gallingerj** [comment]
I think we should change the language of the pacing questions: "the workshop moved at a pace that made it easy for me to learn and participate".

We should also account for it potentially being too slow. The scale should be from too slow --> too fast instead of too fast --> just right. Alternatively, we could introduce another question that asks if it was too slow, i.e. "the workshop moved at a pace that was slower than needed to learn and participate".

**Comment by gallingerj** [comment]
I think we should also be able to link the pre- and post- assessments. That way, we can see if there's a relationship between the demographic information and learning outcomes. Steph, I think we had originally talked about doing a paper assessment to facilitate this (pre- and post- on different sides of one page) and to ensure a 100% completion rate? If there are questions that we want to know ahead of the conference in order to adapt our content, those could be sent separately in an email, Google form, etc.  I will upload a paper template that I've used before for consideration.

**Comment by daniellecrobinson** [comment]
Ah, in that case I can un-anonymize the preworkshop survey with names/emails

**Comment by gallingerj** [comment]
I've uploaded the file here: https://github.com/mozillascience/friendly-github/blob/master/assets/GH%20assessment.docx

@daniellecrobinson Or we can ask questions that will influence our instructional content, decisions, etc. in advance (by anonymous Google form) and ask demographic questions with paper on the day of the workshop. If there are 1-2 redundant questions that may be OK.

**Comment by daniellecrobinson** [comment]
@gallingerj let me know what you think of this.... https://docs.google.com/forms/d/e/1FAIpQLSft9j-VxZdqszo747JBtigIggkWDoe17H8SrYj12IpR6NK7Fg/viewform?usp=sf_link

**Comment by stephwright** [comment]
Steph will put together paper assessment and will share file when done.

**Comment by stephwright** [comment]
Pre/post paper assessment is here: https://docs.google.com/document/d/1_N5ZSVvcNUp6F5xLPGw9JzeeZAhmMCtwFY6z6gL7vXY/edit?usp=sharing

**Comment by stephwright** [comment]
Merging w/ Issue #21

**Comment by stephwright** [comment]
Steph will make a matrix for second side to save space.

**Comment by stephwright** [comment]
Updated
