### ISSUE TITLE
Create mid-workshop assessment

### ISSUE THREAD

**Issue by stephwright** [mozillascience/friendly-github#5]
Quick form to fill out before break re: pace, clear communication, confusion points

**Comment by gallingerj** [comment]
You could use the Software Carpentry model; take a note of something you liked on one sticky note (i.e. green) and something you'd like to see improved on another (i.e. red). Folks will have these sticky notes on hand because that's how they signal if they become confused (i.e. red sticky note on laptop) or finish an exercise (i.e. green sticky note on laptop).

**Comment by stephwright** [comment]
Yes!  I like it!  Let's do it!
I'll start a supply list.  See #16
